### ISSUE TITLE
Extra toolbelt research should probably have vanilla toolbelt research as a prerequisite?

### ISSUE THREAD

**Issue by tornewuff** [Aidiakapi/qol_research#3]
The research for adding more toolbelts should probably require you to research the vanilla toolbelt upgrade first by default, the same way that the logistic request slots one does?

**Comment by Aidiakapi** [comment]
The reason that toolbelts don't require the vanilla research, is because it only requires red science. For modpacks (notably Bobs Angels), getting to green science takes a significantly longer time, and it's therefore nice to the second toolbelt before that point.

Regardless of whether that's the right decision or not, it'll be irrelevant soon, since 0.17 changes the way toolbelts work, and the research might be entirely removed from the mod. I'm not sure, we'll have to wait and see how it'll eventually work.
