### ISSUE TITLE
error

### ISSUE THREAD

**Issue by DeadlyKitten37** [Aidiakapi/qol_research#9]
![image](https://user-images.githubusercontent.com/53106272/114675644-b68b3980-9cc5-11eb-9b6e-61521a65b666.png)

```1,20,crafting-speed,100*L,automation-science-pack,logistic-science-pack,150*L,chemical-science-pack,225*L,production-science-pack,300*L,utility-science-pack,500*L,1000*L,space-science-pack,inventory-size,175*L,production-science-pac,500*2^L,mining-speed,movement-speed,player-reach,5,1,6,5,20,0,0,2,20,1,1,3,5,10,3,1,4,5,30,2,1,3,1,4,6,10,3,1,6,7,30,3,1,3,1,4,1,6,6,10,3,1,8,9,30,4,1,3,1,4,1,6,1,8,8,10,3,1,10,11,30,5,1,3,1,4,1,6,1,8,1,10,10,10,3,1,10,12,60,6,1,3,1,4,1,6,1,8,1,10,1,13,14,6,2,10,0,0,5,20,1,1,3,2,10,1,1,4,15,30,2,1,3,1,4,1,10,1,1,6,7,30,3,1,3,1,4,1,6,1,10,1,1,10,9,30,4,1,3,1,4,1,6,1,10,1,10,1,1,0,11,30,6,1,3,1,4,1,6,1,10,1,13,1,16,0,10,1,1,13,17,60,5,1,3,1,4,1,6,1,10,1,13,18,6,4,30,0,0,2,20,1,1,3,4,20,2,1,4,5,30,2,1,3,1,4,5,10,3,1,6,7,30,3,1,3,1,4,1,6,5,10,3,1,8,9,30,4,1,3,1,4,1,6,1,8,5,10,3,1,10,11,30,5,1,3,1,4,1,6,1,8,1,10,5,20,3,1,13,17,60,6,1,3,1,4,1,6,1,8,1,10,1,13,19,6,5,10,0,0,2,20,1,1,3,5,5,3,1,4,5,30,2,1,3,1,4,5,5,3,1,6,7,30,3,1,3,1,4,1,6,5,5,3,1,10,9,30,4,1,3,1,4,1,6,1,10,5,5,3,1,8,11,30,5,1,3,1,4,1,6,1,10,1,8,10,5,3,1,13,12,60,6,1,3,1,4,1,6,1,10,1,8,1,13,20,6,3,5,0,0,2,20,1,1,3,4,3,2,1,4,5,30,2,1,3,1,4,3,3,3,1,6,7,30,3,1,3,1,4,1,6,4,4,3,1,8,9,30,4,1,3,1,4,1,6,1,8,5,5,3,1,10,11,30,5,1,3,1,4,1,6,1,8,1,10,0,5,3,1,13,12,60,6,1,3,1,4,1,6,1,8,1,10,1,13```

**Comment by Aidiakapi** [comment]
As the error message says, the problem is prerequisites of the 5th tier of inventory size. It says that the ID is empty, and if you open the config in the editor, you can see that you do indeed have an empty prerequisite in there.

![image](https://user-images.githubusercontent.com/1985013/114722759-5b475e80-9d3a-11eb-807a-b2b607623bac.png)

I'll probably be able to put a diagnostic for the specific error of an empty ingredient name/prerequisite in the configuration editor.
